
services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_service
    ports:
      - "8000:8000"
    networks:
      - airflow_network
    env_file:
      - ./backend/.env
    volumes:
      - ./agents:/app/agents
      - ./test_workflow:/app/test_workflow
      - ./logs:/app/logs
      - ./postgres_db:/app/postgres_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: streamlit_app
    ports:
      - "8501:8501"
    networks:
      - airflow_network
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy

networks:
  airflow_network:
    external: true
